# Bias / Variance 

Bias  variance trade of underfitting and overfitting:
1. Regularization:
    - Lasso(L1)
    - Ridge (L2)
2. Cross Validation:

## 1. Regularization

* Lasso: will ommit the variables which aren't contributing high to the prediction of label
* Ridde: will try to minimize the difference of negative and possitive of coefficient of dataset.
* Elastic Net: it contribution of lasso and ridge

In [119]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_boston

In [120]:
boston = load_boston()
boston

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [121]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename', 'data_module'])

In [122]:
boston.data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [123]:
boston.target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [124]:
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [125]:
boston.DESCR

".. _boston_dataset:\n\nBoston house prices dataset\n---------------------------\n\n**Data Set Characteristics:**  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate per $10,000

In [126]:
x=boston.data
y=boston.target

In [127]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size =.33, random_state=47)

In [128]:
x_train.shape

(339, 13)

In [129]:
y_train.shape

(339,)

In [130]:
x_test.shape

(167, 13)

In [131]:
y_test.shape

(167,)

In [132]:
lm = LinearRegression()
lm.fit(x_train,y_train)

LinearRegression()

In [133]:
lm.score(x_train,y_train)

0.7665529829880268

In [134]:
lm.coef_

array([-1.10843155e-01,  3.66995321e-02,  8.74460015e-03,  3.32218225e+00,
       -1.71846638e+01,  4.81511727e+00, -1.38022222e-02, -1.44146494e+00,
        2.63392383e-01, -1.17496784e-02, -9.25130518e-01,  9.07087108e-03,
       -4.12146398e-01])

In [135]:
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [136]:
predlm = lm.predict(x_test)
predlm

array([15.84192559, 32.20569827, 24.42230605, 30.84928633, 27.31927564,
       19.65311852, 23.05432432, 31.7229619 , 32.45933432, 22.63205367,
       24.91948411, 27.15339443, 20.16729816, 27.95837435, 32.02171343,
       10.19889234, 36.05901216, 14.96179519, 11.66767994, 15.55657875,
       35.22194463, 22.20185653, 38.8142947 , 20.4290284 , 28.49163796,
       19.08044635, 24.02797912, 20.78907881, 19.65030776, 26.41697272,
       14.14117934, 25.89121978, 17.77544803,  8.02793933, 32.83228276,
       19.02926719, 12.35104367, 27.13926668, 22.64549403, 18.75190375,
       23.67614267, 25.19654715, 37.31343761, 21.2740326 , 32.30876439,
       20.32537386,  7.41789113, 28.06144027, 36.28142462, 21.53339694,
       28.92419026, 23.82647841,  7.34739041, 24.23067937,  6.12843722,
       21.90316166, 18.29285279, 13.19056989,  5.99004693, 30.08061674,
       12.37541899, 17.83046748, 18.15297944, 19.08005857, 42.19993227,
       22.50076808, 20.52857282, 23.9328331 , 25.64429237, 27.51

In [137]:
mean_squared_error(y_test,predlm)

27.42072820908459

In [138]:
np.sqrt(mean_squared_error(y_test,predlm))

5.236480517397595

In [139]:
## Regularization :: L1 and L2 Regularization

In [140]:
from sklearn.linear_model import Lasso,Ridge

### a) Lasso

In [141]:
"""Will reduce the coefficient to zero (those features are not informative)"""
# alpha values could be --> .0001, .001, .01, .1, 1, 10 --> Higher values reduces all coefficient towards 0 and impact output
# Default value of alpha = 1.0
# alpha = .01

ls = Lasso(alpha = .0001) # Deafault value of lasso(alpha=1.0)
ls.fit(x_train,y_train)
print(ls.score(x_train,y_train))

predls = ls.predict(x_test)
print('mean_square_error', mean_squared_error(y_test,predls))
print('mean_squared_error', np.sqrt(mean_squared_error(y_test,predls)))

0.7665529400345414
mean_square_error 27.420686040715136
mean_squared_error 5.23647649099231


In [142]:
ls.coef_

array([-1.10824693e-01,  3.67066154e-02,  8.58729659e-03,  3.32038457e+00,
       -1.71509902e+01,  4.81528448e+00, -1.38318082e-02, -1.44099502e+00,
        2.63304303e-01, -1.17526095e-02, -9.24709393e-01,  9.07325563e-03,
       -4.12162696e-01])

### b) Ridge

In [143]:
#try to minimize the coefficient variance

rd =Ridge(alpha = .0001)
rd.fit(x_train,y_train)
print(rd.score(x_train,y_train))

predrd = rd.predict(x_test)
print('mean_square_error', mean_squared_error(y_test,predrd))
print('mean_squared_error', np.sqrt(mean_squared_error(y_test,predrd)))

0.7665529828886577
mean_square_error 27.420755562391204
mean_squared_error 5.236483129199521


In [144]:
rd.coef_

array([-1.10842268e-01,  3.66998800e-02,  8.73686616e-03,  3.32215005e+00,
       -1.71830063e+01,  4.81513570e+00, -1.38038984e-02, -1.44144307e+00,
        2.63388003e-01, -1.17498140e-02, -9.25109364e-01,  9.07099128e-03,
       -4.12146425e-01])

###  c) Elastic Net

In [145]:
#Elastic Net is combination of both lasso & ridge

from sklearn.linear_model import ElasticNet
enr = ElasticNet(alpha = .0001)
enr.fit(x_train,y_train)
print(enr.score(x_train,y_train))

predenr = enr.predict(x_test)
print('mean_square_error', mean_squared_error(y_test,predenr))
print('mean_squared_error', np.sqrt(mean_squared_error(y_test,predenr)))

0.7665498739655398
mean_square_error 27.425497789971285
mean_squared_error 5.23693591616045


In [146]:
enr.coef_

array([-1.10686350e-01,  3.67611422e-02,  7.37727002e-03,  3.31588047e+00,
       -1.68916472e+01,  4.81825513e+00, -1.40961471e-02, -1.43758689e+00,
        2.62619134e-01, -1.17737697e-02, -9.21396641e-01,  9.09208744e-03,
       -4.12160129e-01])

In [147]:
from sklearn.svm import SVR

svr = SVR(kernel = "linear")
svr.fit(x_train,y_train)
print(svr.score(x_train,y_train))
pred_y = svr.predict(x_test)
pred_y
print('Mean_squared_error',np.sqrt(mean_squared_error(y_test,pred_y)))



svr = SVR(kernel = "poly")
svr.fit(x_train,y_train)
print(svr.score(x_train,y_train))
pred_y = svr.predict(x_test)
pred_y
print('Mean_squared_error',np.sqrt(mean_squared_error(y_test,pred_y)))




svr = SVR(kernel = "rbf")
svr.fit(x_train,y_train)
print(svr.score(x_train,y_train))
pred_y = svr.predict(x_test)
pred_y
print('Mean_squared_error',np.sqrt(mean_squared_error(y_test,pred_y)))

0.7390428007452163
Mean_squared_error 5.684778067251567
0.21984205036201276
Mean_squared_error 8.558604079793616
0.22924996554545518
Mean_squared_error 8.542156511125972


In [148]:
from sklearn.svm import SVR

KernelList = ["linear", "poly", "rbf"]
for i in KernelList:
    svr =SVR(kernel = i)
    svr.fit(x_train,y_train)
    print("Score of ",i, ": ", svr.score(x_train,y_train))
    svr.predict(x_test)
    print("Mean_squared_error of",i, ": ", np.sqrt(mean_squared_error(y_test,pred_y)))

Score of  linear :  0.7390428007452163
Mean_squared_error of linear :  8.542156511125972
Score of  poly :  0.21984205036201276
Mean_squared_error of poly :  8.542156511125972
Score of  rbf :  0.22924996554545518
Mean_squared_error of rbf :  8.542156511125972


## 2. Cross Validation

Cross validation are of 3 type:
1. Hold-out Cross Validation. (70%-30%/ train_test_split)
2. k-fold Cross Validation. 
3. LOOCU Leave One Out Cross Validation

In [150]:
import pandas as pd
import seaborn as sns
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import warnings
warnings.filterwarnings('ignore')

In [151]:
iris = load_iris()
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [152]:
print(iris.data)
print(iris.feature_names)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [153]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [154]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [155]:
ds = pd.DataFrame(data = iris.data)
print(ds)

       0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]


In [156]:
sns.pairplot(ds)

In [157]:
x = iris.data
y= iris.target

x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = .22, random_state = 43)

#### MultinomialNB

In [158]:
mnb =MultinomialNB()
mnb.fit(x_train,y_train)
predmnb = mnb.predict(x_test)
print(accuracy_score(y_test,predmnb))
print(confusion_matrix(y_test,predmnb))
print(classification_report(y_test,predmnb))

1.0
[[14  0  0]
 [ 0 10  0]
 [ 0  0  9]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00         9

    accuracy                           1.00        33
   macro avg       1.00      1.00      1.00        33
weighted avg       1.00      1.00      1.00        33



#### Support Vector Classifier

In [159]:
svc = SVC(kernel='rbf') #kernel default is rbf
svc.fit(x_train,y_train)
predsvc = svc.predict(x_test)
print(accuracy_score(y_test,predsvc))
print(confusion_matrix(y_test,predsvc))
print(classification_report(y_test,predsvc))

0.9393939393939394
[[14  0  0]
 [ 0 10  0]
 [ 0  2  7]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.83      1.00      0.91        10
           2       1.00      0.78      0.88         9

    accuracy                           0.94        33
   macro avg       0.94      0.93      0.93        33
weighted avg       0.95      0.94      0.94        33



#### Decision Tree Classifier

In [160]:
#Decision Tree classifier(criterion = 'gini')  --->by Deafult
#Decision Tree classifier (criterion = 'entropy')
#gini and entropy

dtc = DecisionTreeClassifier()
dtc.fit(x_train,y_train)
preddtc = dtc.predict(x_test)
print(accuracy_score(y_test,preddtc))
print(confusion_matrix(y_test,preddtc))
print(classification_report(y_test,preddtc))

0.9393939393939394
[[14  0  0]
 [ 0 10  0]
 [ 0  2  7]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.83      1.00      0.91        10
           2       1.00      0.78      0.88         9

    accuracy                           0.94        33
   macro avg       0.94      0.93      0.93        33
weighted avg       0.95      0.94      0.94        33



#### K-Neighbors Classifier

In [185]:
kn = KNeighborsClassifier()
kn.fit(x_train,y_train)
predkn = kn.predict(x_test)
print(accuracy_score(y_test, predkn))
print(confusion_matrix(y_test, predkn))
print(classification_report(y_test, predkn))

1.0
[[14  0  0]
 [ 0 10  0]
 [ 0  0  9]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00         9

    accuracy                           1.00        33
   macro avg       1.00      1.00      1.00        33
weighted avg       1.00      1.00      1.00        33



### converting it to dataframe

In [164]:
df1 = pd.DataFrame(predsvc)
df1.to_csv('svc_prediction.csv')

In [166]:
from sklearn.model_selection import cross_val_score

score = cross_val_score(mnb,x,y, cv = 5)
print(score)
print(score.mean())
print(score.std())

[1.         0.96666667 0.9        0.9        1.        ]
0.9533333333333334
0.04521553322083511


##### Kfold

In [186]:
from sklearn.model_selection import KFold
# KFold (n_splits = 5)

kfold =KFold(5)
score = cross_val_score(mnb,x,y, cv = kfold)
print(score)
print(score.mean())
print(score.std())

[0.96666667 0.66666667 0.         0.33333333 0.        ]
0.3933333333333333
0.37853518844209044


In [167]:
score = cross_val_score(svc,x,y, cv = 5)
print(score)
print(score.mean())
print(score.std())

[0.96666667 0.96666667 0.96666667 0.93333333 1.        ]
0.9666666666666666
0.02108185106778919


In [168]:
score = cross_val_score(dtc,x,y, cv = 5)
print(score)
print(score.mean())
print(score.std())

[0.96666667 0.96666667 0.9        0.96666667 1.        ]
0.9600000000000002
0.03265986323710903


### Prediction

In [169]:
import numpy as np
s = np.array([5.9, 3., 5.1, 1.8])
s

array([5.9, 3. , 5.1, 1.8])

In [170]:
s.shape

(4,)

In [173]:
s=s.reshape(1,-1)

In [174]:
s.shape

(1, 4)

In [175]:
predvalue = svc.predict(s)
predvalue

array([2])

In [176]:
# same process using user defined function

def testpredict(s):
    s = s.reshape(1,-1)
    print("s.shape is ", s.shape)
    predval = svc.predict(s)
    print(predval)

In [177]:
s = np.array([6.2,3.4,5.4,2.3])
testpredict(s)

s.shape is  (1, 4)
[2]


## Saving the best model

### 1. First method

In [178]:
#from sklearn.externals import joblib

import joblib

#save the model as a object file
joblib.dump(svc,'svcfile.obj')

#load the model from the file
dtc_from_joblib = joblib.load('svcfile.obj')

#use the loaded model to make predictions
dtc_from_joblib.predict(x_test)

array([0, 0, 1, 1, 2, 0, 2, 1, 1, 1, 0, 1, 2, 0, 1, 1, 0, 0, 2, 2, 0, 0,
       0, 2, 1, 2, 0, 1, 0, 0, 1, 0, 1])

### 2. Second Method

In [179]:
import pickle

filename = 'svcfile.obj'
pickle.dump(svc, open(filename,'wb'))

#load the model from the disk
loaded_model = pickle.load(open(filename,'rb'))

loaded_model.predict(x_test)

array([0, 0, 1, 1, 2, 0, 2, 1, 1, 1, 0, 1, 2, 0, 1, 1, 0, 0, 2, 2, 0, 0,
       0, 2, 1, 2, 0, 1, 0, 0, 1, 0, 1])